/*
 * This file was generated by the Gradle 'init' task.
 *
 * This project uses @Incubating APIs which are subject to change.
 */

plugins {
    `java-library`
    `maven-publish`
    application
    jacoco
    id("com.github.johnrengelman.shadow") version "8.1.1"
}

repositories {
    mavenLocal()
    maven {
        url = uri("https://repository.mulesoft.org/nexus/content/repositories/public/")
    }

    maven {
        url = uri("https://repo.maven.apache.org/maven2/")
    }
}

dependencies {
    api(libs.org.hyperledger.fabric.fabric.gateway.java)
    api(libs.org.hyperledger.fabric.chaincode.java.fabric.chaincode.shim)
    api(libs.com.owlike.genson)
    implementation("com.github.everit-org.json-schema:org.everit.json.schema:1.12.2")
}

group = "s16749"
version = "1.0-SNAPSHOT"
description = "Archetype - EncryptionSmartContract"
java.sourceCompatibility = JavaVersion.VERSION_1_8

publishing {
    publications.create<MavenPublication>("maven") {
        from(components["java"])
    }
}

application {
    mainClass = "org.hyperledger.fabric.contract.ContractRouter"
}

apply(plugin = "com.github.johnrengelman.shadow")